# Generated by Django 3.2.9 on 2021-11-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название комлпетующих')),
                ('price', models.CharField(max_length=200, verbose_name='Цена')),
                ('image', models.ImageField(upload_to='image/', verbose_name='Изоображение')),
                ('description', models.TextField(max_length=5000, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Комлпектующие',
                'verbose_name_plural': 'Комлпетующие',
            },
        ),
        migrations.CreateModel(
            name='Systemunit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название системного блока')),
                ('price', models.CharField(max_length=200, verbose_name='Цена')),
                ('image', models.ImageField(upload_to='image/', verbose_name='Изоображение')),
                ('description', models.TextField(max_length=5000, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Системник',
                'verbose_name_plural': 'Системники',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Ноутбук', 'verbose_name_plural': 'Ноутбуки'},
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=1, max_length=5000, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='image/', verbose_name='Изоображение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='название ноутбука'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=200, verbose_name='Цена'),
        ),
    ]
