# Generated by Django 3.2.9 on 2021-11-08 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20211108_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessories',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='systemunit',
            name='image',
        ),
    ]
