# Generated by Django 3.2.9 on 2021-11-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20211108_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название комлпетующих')),
                ('price', models.CharField(max_length=200, verbose_name='Цена')),
                ('image', models.ImageField(upload_to='image/', verbose_name='Изоображение')),
                ('description', models.TextField(max_length=5000, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Комлпектующие',
                'verbose_name_plural': 'Комлпетующие',
            },
        ),
        migrations.CreateModel(
            name='Noteboo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название ноутбука')),
                ('price', models.CharField(max_length=200, verbose_name='Цена')),
                ('image', models.ImageField(upload_to='image/', verbose_name='Изоображение')),
                ('description', models.TextField(max_length=5000, verbose_name='Описание')),
                ('haracteristick', models.TextField(max_length=5000, verbose_name='Характеристики')),
            ],
            options={
                'verbose_name': 'Ноутбук',
                'verbose_name_plural': 'Ноутбуки',
            },
        ),
        migrations.CreateModel(
            name='Systemunit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название системного блока')),
                ('price', models.CharField(max_length=200, verbose_name='Цена')),
                ('image', models.ImageField(upload_to='image/', verbose_name='Изоображение')),
                ('description', models.TextField(max_length=5000, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Системник',
                'verbose_name_plural': 'Системники',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Не заполнять', 'verbose_name_plural': 'Не заполнять'},
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='название'),
        ),
    ]
