# Generated by Django 3.2.9 on 2021-11-08 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20211108_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Open',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название продукта')),
                ('price', models.CharField(max_length=200, verbose_name='Цена')),
                ('image', models.ImageField(upload_to='image/', verbose_name='Изоображение')),
                ('description', models.TextField(max_length=5000, verbose_name='Описание')),
                ('haracteristick', models.TextField(max_length=5000, verbose_name='Характеристики')),
                ('person', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Open',
                'verbose_name_plural': 'Open',
            },
        ),
    ]
