# Generated by Django 3.2.9 on 2021-11-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_open_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='open',
            name='person',
        ),
        migrations.AddField(
            model_name='open',
            name='year',
            field=models.CharField(default='', max_length=200, verbose_name='Год выпуска'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='noteboo',
            name='image',
            field=models.TextField(max_length=5000, verbose_name='URL изоображения'),
        ),
    ]
