# Generated by Django 3.2.9 on 2021-11-10 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20211110_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='open',
            name='description',
        ),
        migrations.RemoveField(
            model_name='open',
            name='haracteristick',
        ),
        migrations.RemoveField(
            model_name='open',
            name='image',
        ),
        migrations.RemoveField(
            model_name='open',
            name='name',
        ),
        migrations.RemoveField(
            model_name='open',
            name='price',
        ),
        migrations.RemoveField(
            model_name='open',
            name='product',
        ),
        migrations.RemoveField(
            model_name='open',
            name='year',
        ),
        migrations.AddField(
            model_name='open',
            name='noteboo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shop.noteboo'),
            preserve_default=False,
        ),
    ]
