# Generated by Django 3.2.9 on 2021-11-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20211110_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='open',
            name='noteboo',
        ),
        migrations.AddField(
            model_name='open',
            name='description',
            field=models.TextField(default='', max_length=5000, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='open',
            name='haracteristick',
            field=models.TextField(default='', max_length=5000, verbose_name='Характеристики'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='open',
            name='image',
            field=models.TextField(default='', max_length=5000, verbose_name='URL изоображения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='open',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='название продукта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='open',
            name='price',
            field=models.CharField(default='', max_length=200, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='open',
            name='year',
            field=models.CharField(default='', max_length=200, verbose_name='Год выпуска'),
            preserve_default=False,
        ),
    ]
