# Generated by Django 3.2.9 on 2021-11-11 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_promo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo', models.CharField(max_length=200, verbose_name='Промокод')),
                ('number', models.TextField(max_length=11, verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Promocod',
                'verbose_name_plural': 'Promocod',
            },
        ),
        migrations.DeleteModel(
            name='Promo',
        ),
        migrations.RemoveField(
            model_name='open',
            name='description',
        ),
        migrations.RemoveField(
            model_name='open',
            name='haracteristick',
        ),
        migrations.RemoveField(
            model_name='open',
            name='image',
        ),
        migrations.RemoveField(
            model_name='open',
            name='name',
        ),
        migrations.RemoveField(
            model_name='open',
            name='price',
        ),
        migrations.AddField(
            model_name='open',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product'),
        ),
    ]
