# Generated by Django 3.2.9 on 2021-11-11 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20211111_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='open',
            options={},
        ),
        migrations.AlterField(
            model_name='open',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shop.noteboo'),
            preserve_default=False,
        ),
    ]
