# Generated by Django 3.2.9 on 2021-11-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20211111_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='open',
            options={'verbose_name': 'Open', 'verbose_name_plural': 'Open'},
        ),
        migrations.RemoveField(
            model_name='open',
            name='product',
        ),
        migrations.AddField(
            model_name='open',
            name='description',
            field=models.TextField(default='', max_length=5000, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='open',
            name='haracteristick',
            field=models.TextField(default='', max_length=5000, verbose_name='Характеристики'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='open',
            name='image',
            field=models.TextField(default='', max_length=5000, verbose_name='URL изоображения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='open',
            name='name',
            field=models.CharField(default=1, max_length=200, verbose_name='название ноутбука'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='open',
            name='price',
            field=models.CharField(default='', max_length=200, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
