# Generated by Django 3.2.9 on 2021-11-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_notepr'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteboo',
            name='sale10',
            field=models.CharField(default='', max_length=200, verbose_name='скидка 10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noteboo',
            name='sale5',
            field=models.CharField(default='', max_length=200, verbose_name='скидка 5'),
            preserve_default=False,
        ),
    ]
