# Generated by Django 3.2.9 on 2021-11-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20211115_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories',
            name='image',
            field=models.TextField(max_length=5000, verbose_name='URL изоображения'),
        ),
    ]
